### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by schneiderpy** [LatinR/web-LatinR2024#12]
Hello Beatriz

I am curious: how do you deploy the website for "Latin-R" .. via Github or directly with a FTP program?
Saludos
Andreas

**Comment by beatrizmilz** [comment]
Hi @schneiderpy !

There is a Workflow with GitHub Actions that renders the website,  so all the `.html` files are generated again when there is a push in the repository.

https://github.com/LatinR/latinrweb-v2/actions/workflows/update-website.yaml

The code for this workflow is available here: https://github.com/LatinR/latinrweb-v2/blob/main/.github/workflows/update-website.yaml

If the answer is not clear, or not what you asked, let me know!! :)

**Comment by schneiderpy** [comment]
Hi @beatrizmilz 

Thank you for your prompt reply.
It is still confusing, since you are deploying from Github to your own domain (latin-r.com).  Since everyone can clone the repo, I am afraid that someone can use it for cybercrime activities etc.
For this reason I was (I am still) interested to know if one can deploy on a local machine and than upload with an FTP program to a hosting service? I think that this might be more secure, since the website I want to creat is intented to be a mixture of a business side and a blog with R-things.

**Comment by rivaquiroga** [comment]
@schneiderpy, if you want to avoid people cloning your repository, you can keep it private. A private repository can be deployed using GitHub Pages or other services like Netlify (although for GitHub Pages you need a pro account; for public repos the service is free)

**Comment by schneiderpy** [comment]
Thank you @rivaquiroga 
I am aware of the private repo on Github, but my question still is if I can deploy a Quarto website/blog on my local machine and then upload it with an FTP program (e.g. FileZilla)
