### ISSUE TITLE
Calendar page

### ISSUE THREAD

**Issue by jtrecenti** [LatinR/web-LatinR2024#26]
@TuQmano Hi Juan! Here is @beatrizmilz (im not with my computer here)
I added on the website the first version of the program using toastui.
Feel free to add or change anything. I wont be able to make any changes this week.

https://github.com/LatinR/latinrweb-v2/blob/c920064b0f94a77d255b417422822c59872d3a27/cronograma/programa/index.qmd#L32-L124

**Comment by TuQmano** [comment]
We can close this one, no @beatrizmilz ?

**Comment by beatrizmilz** [comment]
> We can close this one, no @beatrizmilz ?

I created this quite a while ago, and I don't even remember much about it. So I guess we can close it 😆
