### ISSUE TITLE
Actualizar los datos 2024

### ISSUE THREAD

**Issue by yabellini** [LatinR/web-LatinR2024#29]

**Comment by beatrizmilz** [comment]
I did not do this thinking would be good to do the https://github.com/LatinR/latinrweb-v2/issues/30 first! (thanks Yani for creating this issue!)

**Comment by yabellini** [comment]
@beatrizmilz I will now create a PR with the changes I just did so you can check it.  We can discard all my few changes, no problem.  But we really need to update the info, because people are not finding the information to send their proposals and sponsors are not finding the info to see if they are interested in supporting this edition.

**Comment by yabellini** [comment]
Done via https://github.com/LatinR/latinrweb-v2/pull/36 and https://github.com/LatinR/latinrweb-v2/pull/38
