### ISSUE TITLE
Guardar los datos edicion 2023

### ISSUE THREAD

**Issue by yabellini** [LatinR/web-LatinR2024#30]

**Comment by beatrizmilz** [comment]
Hi @yabellini @rivaquiroga ! I have been thinking about this, but not sure how to proceed.

What do you think is the best way to do this? clone the repo and save the clone as of 2023, and redirect the github.io website in the domain? Or you have other ideas?

**Comment by yabellini** [comment]
I copied the docs folder renamed as 2023 to the docs folder, and with that, when we write latin-r.com/2023, we can see the old site. 

It works locally.   Do you think this is not a good idea?  I'm also ok with fork and then create subdomains, like 2023.latin-r.com, etc.

**Comment by yabellini** [comment]
@beatrizmilz check this PR: https://github.com/LatinR/latinrweb-v2/pull/31

**Comment by beatrizmilz** [comment]
@rivaquiroga you have access to the domain config, right?
Do you think you can create a subdomain to 2023 and redirect it to the github.io website?
This is a fork of the website with the code from 2023:
https://latinr.github.io/latinrweb-v2_2023/

**Comment by rivaquiroga** [comment]
I'll check and let you know!

**Comment by rivaquiroga** [comment]
@beatrizmilz, the 2023 website is live now at https://2023.latin-r.com/

**Comment by beatrizmilz** [comment]
> @beatrizmilz, the 2023 website is live now at https://2023.latin-r.com/

Thank you Riva!
I think we can add this link in the navbar, as "past events" or something related :)

**Comment by rivaquiroga** [comment]
Update: the link is now 2023.latinr.org
I like the idea of "past events" in the navbar!
