### ISSUE TITLE
Write blog post with call of proposal 2024

### ISSUE THREAD

**Issue by yabellini** [LatinR/web-LatinR2024#32]

**Comment by yabellini** [comment]
Thie PR have the blog post with the call of proposals: https://github.com/LatinR/latinrweb-v2/pull/33

**Comment by beatrizmilz** [comment]
ES: https://latin-r.com/blog/es/2024-07-09-presentacion-trabajos-2024.html
PT: https://latin-r.com/pt/blog/pt/2024-07-09-apresentacao-trabalhos-2024.html
EN: https://latin-r.com/en/blog/en/2024-07-09-call-for-papers-2024.html
