### ISSUE TITLE
Add "past events" section

### ISSUE THREAD

**Issue by rivaquiroga** [LatinR/web-LatinR2024#39]
- [x] **Step 1: Create subdomains for previous editions** (@rivaquiroga)

   - [x] https://2023.latinr.org/
   - [x] https://2022.latinr.org/
   - [x] https://2021.latinr.org/
   - [x] https://2020.latinr.org/
   - [x] https://2019.latinr.org/
   - [x] https://2018.latinr.org/

- [x] **Step 2: Add "Past events" to navbar** (@beatrizmilz)

**Comment by rivaquiroga** [comment]
@beatrizmilz, I'll let you know when all the subdomains are created

**Comment by rivaquiroga** [comment]
done!

**Comment by beatrizmilz** [comment]
Awesome, Riva! 
I added the past events in the navbar.
