### ISSUE TITLE
Add information that the registration is free

### ISSUE THREAD

**Issue by beatrizmilz** [LatinR/web-LatinR2024#45]
@yabellini 
> La otra cosa, algunas personas estan preguntando costo de registro, como siempre en lo on-line es sin costo.  Solo cobrariamos por los tutoriales.  Pero por ahi podemos agregar esa info en la web.  Voy a ir viendo lo del eventbrite.

**Comment by yabellini** [comment]
Eventbrite link: https://www.eventbrite.cl/e/latinr-2024-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-970622687587?aff=oddtdtcreator
