### ISSUE TITLE
Slack join links don't work

### ISSUE THREAD

**Issue by yabellini** [LatinR/web-LatinR2024#69]
This is a new one: https://join.slack.com/t/latin-r/shared_invite/zt-2tespojdh-OpXaVcnzOY_SETtv9hqRSQ

**Comment by beatrizmilz** [comment]
Hi Yani! Thank you for creating the issue, it makes it easier for me to follow up what we need to do. I receive better notifications than Slack (and I don't usually check slack everyday because I don't use it at work).


I'll update it later today, ok? 

I'm at GitHub conf!

**Comment by yabellini** [comment]
I saw your photos!! Enjoy.

**Comment by beatrizmilz** [comment]
Updated @yabellini !
