### ISSUE TITLE
Update courses

### ISSUE THREAD

**Issue by yabellini** [LatinR/web-LatinR2024#70]
Information of workshops is missing from the website

**Comment by beatrizmilz** [comment]
Hi Yani! Is there anywhere I can see the list/table of workshops to add to the website?

**Comment by yabellini** [comment]
Eventbrite links?  Here are the info about times, dates, and titles:

- [x] - [ES] ggplot: https://www.eventbrite.com.ar/e/1045608201277
- [x] - [PT] Evento satelite 1: traslaton al portugues con rOpenSci: https://www.eventbrite.com.ar/e/1045507530167
- [x] - [ES] Intro a GitHub: https://www.eventbrite.com.ar/e/1045617188157
- [x] - [EN] Arrow y DuckDB: https://www.eventbrite.com.ar/e/1044938257457
- [x] - [ES] Dato satelitales: https://www.eventbrite.com.ar/e/1045614801017
- [x] - [PT] Nicho ecologico: https://www.eventbrite.com.ar/e/1045601130127
- [x] - [ES] Shiny - appsilon - https://www.eventbrite.cl/e/optimizando-shiny-consejos-y-trucos-de-rendimiento-tickets-1045595392967
- [x] - [ES] R, Github & Quarto - https://www.eventbrite.cl/e/despliegue-continuo-con-r-github-y-quarto-implementando-buenas-practicas-tickets-1046364954747
- [x] - [ES] Paquetes en R - https://www.eventbrite.cl/e/desarrollo-de-paquetes-en-r-desde-la-idea-hasta-la-implementacion-tickets-1046361845447

Let me know if this is useful.

**Comment by beatrizmilz** [comment]
Thank you! I can use this information to create the page.

**Comment by beatrizmilz** [comment]
@yabellini I think @mauroloprete  added! https://github.com/LatinR/web-LatinR2024/tree/main/cronograma/tutoriales

**Comment by beatrizmilz** [comment]
I'm checking and seems like some tutorials are not online! I'll add them.

**Comment by beatrizmilz** [comment]
Hi Yani! I finished updating this yesterday. Is there any other updates necessary on the website? Thanks! @yabellini

**Comment by yabellini** [comment]
Thank you! I will check and create issues if I find we need to update more information.  Closing this one.
