### ISSUE TITLE
Create a page for the Translaton 

### ISSUE THREAD

**Issue by beatrizmilz** [LatinR/web-LatinR2024#73]
Create page in Markdown for the translaton.
Here are the information from the EventBrite website:

Evento satelite 1: traslaton al portugues con rOpenSci: https://www.eventbrite.com.ar/e/1045507530167

---

Tradução + Hackathon = Traslaton rOpenSci

Monday, November 18
Tradução + Hackathon = Traslaton rOpenSci

O objetivo é que a comunidade R conheça o rOpenSci e se reúna para aprender a contribuir com o projeto de tradução para o português.

Date and time
Monday, November 18 · 5 - 7am PST
Location
Online

About this event

    Event lasts 2 hours

Tradução + Hackathon = Traslatón

O Traslaton rOpenSci é realizado em conjunto com o LatinR

O objetivo é que a comunidade do R conheça o rOpenSci e se reúna para aprender como contribuir com o projeto de tradução ativa do rOpenSci para o português e fazer contribuições durante o Traslatón.

Várias pessoas da comunidade estarão presentes durante as duas horas do evento online para ajudá-lo durante sua contribuição.

Agenda:

- Começaremos com uma explicação de como funciona o processo de tradução, como fazer uma segunda revisão e onde sua ajuda é necessária para progredir na tradução.

- Em seguida, trabalharemos em blocos de 30 minutos e nos reuniremos para ver o progresso que fizemos.

- Explicaremos o processo da primeira revisão, indicaremos onde essa tarefa é necessária e depois voltaremos ao trabalho por 30 minutos.

- Por fim, nos reuniremos novamente para analisar o progresso e organizar como continuaremos a trabalhar.

Trabalharemos com o Guia de desenvolvimento de pacotes do rOpenSci.

Todos que contribuírem para a tradução serão adicionados como autores dessa tradução quando a primeira versão do trabalho final for publicada. Os colaboradores serão convidados a participar do rOpenSci Slack.

**Comment by beatrizmilz** [comment]
https://github.com/LatinR/web-LatinR2024/tree/main/cronograma/translaton

The files are here, do you want to make any changes? @yabellini @pedropark99

**Comment by pedropark99** [comment]
Looks ok to me 😉

**Comment by beatrizmilz** [comment]
Thanks!!
